services:
  postgres:
    image: postgres:16
    container_name: privacy_check_postgres_dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: privacy_check
      POSTGRES_USER: privacy_user
      POSTGRES_PASSWORD: privacy_password
    volumes:
      - privacy_check_pgdata_dev:/var/lib/postgresql/data

  api-dev:
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: dev
    container_name: privacy_check_api_dev
    command: npm run start:dev
    ports:
      - "3270:3270"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://privacy_user:privacy_password@postgres:5432/privacy_check?schema=public"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  privacy_check_pgdata_dev:
